[theme]
primaryColor = "#1C83E1"             # O azul da sua marca
backgroundColor = "#0B0E14"          # Um preto levemente azulado
secondaryBackgroundColor = "#1A1F29" # Sidebar e cards num tom mais claro
textColor = "#E0E0E0"                # Cinza claro para não cansar a vista
font = "sans serif"
